// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/forums": {
    params: {};
  };
  "/signup": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/userdashboard": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/forums" | "/signup" | "/login" | "/userdashboard";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/forums.tsx": {
    id: "routes/forums";
    page: "/forums";
  };
  "routes/signup.tsx": {
    id: "routes/signup";
    page: "/signup";
  };
  "routes/login.tsx": {
    id: "routes/login";
    page: "/login";
  };
  "routes/userdashboard.tsx": {
    id: "routes/userdashboard";
    page: "/userdashboard";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/home": typeof import("./app/routes/home.tsx");
  "routes/forums": typeof import("./app/routes/forums.tsx");
  "routes/signup": typeof import("./app/routes/signup.tsx");
  "routes/login": typeof import("./app/routes/login.tsx");
  "routes/userdashboard": typeof import("./app/routes/userdashboard.tsx");
};