// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/forums": {
    params: {};
  };
  "/create-forum": {
    params: {};
  };
  "/forum/:forumId": {
    params: {
      "forumId": string;
    };
  };
  "/messages": {
    params: {};
  };
  "/signup": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/userdashboard": {
    params: {};
  };
  "/api/analyzeMessages": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/forums" | "/create-forum" | "/forum/:forumId" | "/messages" | "/signup" | "/login" | "/userdashboard" | "/api/analyzeMessages";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/forums.tsx": {
    id: "routes/forums";
    page: "/forums";
  };
  "routes/create-forum.tsx": {
    id: "routes/create-forum";
    page: "/create-forum";
  };
  "routes/forum-detail.tsx": {
    id: "routes/forum-detail";
    page: "/forum/:forumId";
  };
  "message/message.tsx": {
    id: "message/message";
    page: "/messages";
  };
  "routes/signup.tsx": {
    id: "routes/signup";
    page: "/signup";
  };
  "routes/login.tsx": {
    id: "routes/login";
    page: "/login";
  };
  "routes/userdashboard.tsx": {
    id: "routes/userdashboard";
    page: "/userdashboard";
  };
  "api/analyzeMessages.ts": {
    id: "api/analyzeMessages";
    page: "/api/analyzeMessages";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/home": typeof import("./app/routes/home.tsx");
  "routes/forums": typeof import("./app/routes/forums.tsx");
  "routes/create-forum": typeof import("./app/routes/create-forum.tsx");
  "routes/forum-detail": typeof import("./app/routes/forum-detail.tsx");
  "message/message": typeof import("./app/message/message.tsx");
  "routes/signup": typeof import("./app/routes/signup.tsx");
  "routes/login": typeof import("./app/routes/login.tsx");
  "routes/userdashboard": typeof import("./app/routes/userdashboard.tsx");
  "api/analyzeMessages": typeof import("./app/api/analyzeMessages.ts");
};